import { exportToSvg } from "@excalidraw/excalidraw";
import {
  AppState,
  BinaryFiles,
} from "@excalidraw/excalidraw/types";
import type { ExcalidrawElement } from "@excalidraw/excalidraw/element/types";

/**
 * Frame element with required properties
 */
export type FrameElement = ExcalidrawElement & {
  type: "frame";
  name: string;
  id: string;
};

/**
 * Result of exporting a frame to SVG
 */
export interface FrameExport {
  frameName: string;
  theme: "light" | "dark";
  svg: string;
}

/**
 * Check if an element is an exportable frame
 * @param element - The element to check
 * @returns true if the element is a frame with name starting with "export_"
 */
export function isExportableFrame(element: ExcalidrawElement): boolean {
  return (
    element.type === "frame" &&
    element.name !== null &&
    element.name !== undefined &&
    element.name.startsWith("export_")
  );
}

/**
 * Get the export name from a frame element
 * Removes the "export_" prefix
 * @param frame - The frame element
 * @returns The frame name without the "export_" prefix
 */
export function getFrameExportName(frame: FrameElement): string {
  return frame.name.substring(7); // Remove "export_" prefix
}

/**
 * Get all exportable frames from a list of elements
 * @param elements - All elements in the scene
 * @returns Array of exportable frame elements
 */
export function getExportableFrames(
  elements: readonly ExcalidrawElement[]
): FrameElement[] {
  const frames = elements.filter(isExportableFrame) as FrameElement[];
  console.log("[Frame Exporter] Found frames:", frames.map(f => f.name));
  return frames;
}

/**
 * Get all elements belonging to a specific frame
 * @param elements - All elements in the scene
 * @param frameId - The ID of the frame
 * @returns Array of elements belonging to the frame
 */
export function getFrameElements(
  elements: readonly ExcalidrawElement[],
  frameId: string
): ExcalidrawElement[] {
  return elements.filter((el) => el.frameId === frameId);
}

/**
 * Check if the set of exportable frames has changed
 * @param oldElements - Previous elements
 * @param newElements - Current elements
 * @returns true if frames have been added, removed, or renamed
 */
export function hasFramesChanged(
  oldElements: readonly ExcalidrawElement[],
  newElements: readonly ExcalidrawElement[]
): boolean {
  const oldFrames = getExportableFrames(oldElements);
  const newFrames = getExportableFrames(newElements);

  // Check count
  if (oldFrames.length !== newFrames.length) return true;

  // Check frame names
  const oldNames = new Set(oldFrames.map((f) => f.name));
  const newNames = new Set(newFrames.map((f) => f.name));

  if (oldNames.size !== newNames.size) return true;

  for (const name of oldNames) {
    if (!newNames.has(name)) return true;
  }

  return false;
}

/**
 * Export a single frame to SVG
 * @param frame - The frame element to export
 * @param allElements - All elements in the scene
 * @param appState - The application state
 * @param files - Binary files (images, etc.)
 * @param theme - The theme to export with
 * @returns Promise resolving to FrameExport object
 */
export async function exportFrameToSvg(
  frame: FrameElement,
  allElements: readonly ExcalidrawElement[],
  appState: Partial<AppState>,
  files: BinaryFiles,
  theme: "light" | "dark"
): Promise<FrameExport> {
  // Get elements belonging to this frame
  const frameElements = getFrameElements(allElements, frame.id);

  // Export only the contents, NOT the frame element itself
  const elementsToExport = frameElements;

  // Export to SVG
  console.log(`[Frame Exporter] Exporting frame "${frame.name}" (${theme})`);

  // Prepare appState with exportWithDarkMode set based on theme
  // This is the key to making colors work correctly!
  const exportAppState = {
    ...appState,
    exportScale: 1,
    exportWithBackground: true,
    exportEmbedScene: false,
    exportWithDarkMode: theme === "dark", // ← This triggers dark mode color transformations!
  };

  const svg = await exportToSvg({
    elements: elementsToExport,
    appState: exportAppState,
    files: files,
  });

  // Add metadata as XML comment for reference
  const metadata = `<!--
 Excalidraw Frame Reference
 Frame Name: ${frame.name}
 Theme: ${theme}
 Generated by Excalidraw VSCode Extension
-->`;

  // Insert the comment after the opening <svg> tag
  const svgString = svg.outerHTML.replace(/(<svg[^>]*>)/, `$1\n${metadata}`);

  return {
    frameName: getFrameExportName(frame),
    theme,
    svg: svgString,
  };
}

/**
 * Export all exportable frames to SVG
 * @param elements - All elements in the scene
 * @param appState - The application state
 * @param files - Binary files (images, etc.)
 * @param themes - Array of themes to export (default: ["light", "dark"])
 * @returns Promise resolving to array of FrameExport objects
 */
export async function exportAllFrames(
  elements: readonly ExcalidrawElement[],
  appState: Partial<AppState>,
  files: BinaryFiles,
  themes: ("light" | "dark")[] = ["light", "dark"]
): Promise<FrameExport[]> {
  console.log("[Frame Exporter] exportAllFrames called with", elements.length, "elements");
  const frames = getExportableFrames(elements);
  console.log("[Frame Exporter] Exporting", frames.length, "frames for themes:", themes);
  const exports: FrameExport[] = [];

  for (const frame of frames) {
    for (const theme of themes) {
      try {
        console.log(`[Frame Exporter] Exporting frame "${frame.name}" (${theme})`);
        const exported = await exportFrameToSvg(
          frame,
          elements,
          appState,
          files,
          theme
        );
        exports.push(exported);
        console.log(`[Frame Exporter] Successfully exported ${exported.frameName} (${theme})`);
      } catch (error) {
        console.error(`[Frame Exporter] Failed to export frame ${frame.name}:`, error);
        // Continue with other frames
      }
    }
  }

  console.log("[Frame Exporter] Total exports:", exports.length);
  return exports;
}
